// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7KRRSBYGX1VzojvAwtKze4nw7WeWj2BI',
    appId: '1:988825621508:web:cc4ae249e25f9841549151',
    messagingSenderId: '988825621508',
    projectId: 'trackerappclone',
    authDomain: 'trackerappclone.firebaseapp.com',
    storageBucket: 'trackerappclone.appspot.com',
    measurementId: 'G-ZEFCV21RCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4VvlI5ehlbjHdEUMTcLilZaX8BoiBPw',
    appId: '1:988825621508:android:7c0d2416672c4933549151',
    messagingSenderId: '988825621508',
    projectId: 'trackerappclone',
    storageBucket: 'trackerappclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgG6MnSHn6ULojs2NhzZ1PA2-MeNz50Wg',
    appId: '1:988825621508:ios:b14fdf5efd81a069549151',
    messagingSenderId: '988825621508',
    projectId: 'trackerappclone',
    storageBucket: 'trackerappclone.appspot.com',
    iosBundleId: 'com.ahsan123.trackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgG6MnSHn6ULojs2NhzZ1PA2-MeNz50Wg',
    appId: '1:988825621508:ios:b14fdf5efd81a069549151',
    messagingSenderId: '988825621508',
    projectId: 'trackerappclone',
    storageBucket: 'trackerappclone.appspot.com',
    iosBundleId: 'com.ahsan123.trackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7KRRSBYGX1VzojvAwtKze4nw7WeWj2BI',
    appId: '1:988825621508:web:ecf6b591b9bf513d549151',
    messagingSenderId: '988825621508',
    projectId: 'trackerappclone',
    authDomain: 'trackerappclone.firebaseapp.com',
    storageBucket: 'trackerappclone.appspot.com',
    measurementId: 'G-7SB58H3Y2B',
  );
}
